import os

SCAN_ROOT = os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../scan/')
SCAN_DIR = os.path.join(SCAN_ROOT, 'archive/05.06.2017/')
# TODO: Discriminate between scan static (normal) files and scan dynamic (generated by code) files (archive dir).

BANNERS_DIR = os.path.join(SCAN_DIR, 'banners/')
BANNERS_FAIL_CONN_DIR = os.path.join(BANNERS_DIR, 'fail_conn/')
# TODO: Create if they don't exist.

if not os.path.exists(SCAN_DIR):
    os.makedirs(SCAN_DIR)
if not os.path.exists(BANNERS_DIR):
    os.makedirs(BANNERS_DIR)
if not os.path.exists(BANNERS_FAIL_CONN_DIR):
    os.makedirs(BANNERS_FAIL_CONN_DIR)


SCAN_DB_PATH = os.path.join(SCAN_DIR, 'scan.sqlite')

WHOIS_DIR = os.path.join(SCAN_ROOT, 'whois/')
AR_ZONE_PATH = os.path.join(SCAN_ROOT, 'ar.zone')

WHOIS_TIMEOUT = 20
# Needed to not overload the whois server and avoid a ban.
